### ISSUE TITLE
False positive #2

### ISSUE THREAD

**Issue by leonklingele** [gordonklaus/ineffassign#32]
While scanning the Go source, this tool reports the following lines as an ineffectual assignment to v:

- https://github.com/golang/go/blob/35bb62e60a7779ff82c3067903b3306ff8666471/src/runtime/mfinal_test.go#L60
- https://github.com/golang/go/blob/35bb62e60a7779ff82c3067903b3306ff8666471/src/runtime/stack_test.go#L126

This is not the case as the code is testing [runtime finalizers](https://golang.org/pkg/runtime/#SetFinalizer).

Full warnings:

```
runtime/mfinal_test.go:60:4:warning: ineffectual assignment to v (ineffassign)
runtime/mfinal_test.go:98:3:warning: ineffectual assignment to v (ineffassign)
```

and 

```
runtime/stack_test.go:126:4:warning: ineffectual assignment to s (ineffassign)
```

**Comment by gordonklaus** [comment]
Have you tried removing the reported lines?  I think the tests will still pass, because since 1.11 (or earlier?) Go tracks object lifetimes more intelligently than it used to.  It will free memory even before a variable referencing it goes out of scope if it sees that the variable is no longer used.

**Comment by leonklingele** [comment]
They still pass after removing the `v = nil` assignment! Thanks for helping and sorry for the interruption :)
