### ISSUE TITLE
using ineffassign v0.0.0-20210103220932-664217a59c00 does not work in our build

### ISSUE THREAD

**Issue by bobdonat** [gordonklaus/ineffassign#54]
Prior to the latest version of ineffassign things were working as expected

Using version v0.0.0-20210103220932-664217a59c00 we are seeing:

ineffassign $(find . -name "*.go")
**_-: named files must all be in one directory; have ./operator/mocks/ and ./operator/test/integ/util/
ineffassign: error during loading_**

**Comment by gordonklaus** [comment]
Yes.  Apologies, the latest commit changed the way the tool interprets its arguments.  Instead of interpreting its arguments as a list of files, it interprets its arguments in the same way that the standard Go tools do: see `go help packages` for details.  Try instead `ineffassign ./...`.

I've pushed 8eed68eb605f2ddf507412accb8dd7a595b5c114 to make this more visible.
