### ISSUE TITLE
Why the two cases have different results？

### ISSUE THREAD

**Issue by SMLsk** [gordonklaus/ineffassign#72]
```go
func main() {
        // case 1
	var err = errors.New("1")
	println(err.Error())
	err = errors.New("2") // uncaught ineffectual assignment

        // case 2
	var err2 = errors.New("1")
	if err2 != nil {
		println("ok")
	}
	err2 = errors.New("2") // report: ineffectual assignment to err2
}
```
ineffassign version: last version available
go version: go1.18.2

I thought _**err = errors.New("2")**_ and **_err2 = errors.New("2")_** would report the ineffectual assignment, but actually only the second case will report.

**Comment by gordonklaus** [comment]
Hi.  The first case is possibly not ineffectual because the analyzer has no idea what the call to `err.Error()` might do; it might capture the address of `err` and store it for later use, making the next assignment effectual.

Of course, _we_ know that this doesn't happen because we know how `errors.New` and  `err.Error` work.  But ineffassign doesn't look at types or inter-function data flow.

**Comment by SMLsk** [comment]
Thanks!
