### ISSUE TITLE
Check for reassignment error

### ISSUE THREAD

**Issue by windard** [gordonklaus/ineffassign#74]
In the following code, linter error is raised in first function, but the reassigned err variable in the second function is not found.

```
func doo() (int, int, error) {
    var (
        x, y int
        err  error
    )
    x, err = foo()
    y, err = a(x)
    return x, y, err
}

func do() (x int, y int, err error) {
    x, err = foo()
    y, err = a(x)
    return x, y, err
}

```

**Comment by gordonklaus** [comment]
This is a subtle one :)

In the second function, `a` might panic, and if we recover from that panic then the `err` returned from `foo` will be used (returned).

Now, we do actually know in this case that there is no deferred function so we will not recover from a panic.  Thus, the tool could be updated to keep track of whether any function was deferred.  It's not perfect - a deferred function might not call `recover` - but it's better than nothing.

Please let me know if you would like to submit a PR.  Otherwise I will try to do it at some point.  I expect the change to be very small (keep track of `defer`s and add a conditional in [`maybePanic`](https://github.com/gordonklaus/ineffassign/blob/master/pkg/ineffassign/ineffassign.go#L426)).

**Comment by windard** [comment]
Weather deferred function is called, panic is catched or not,I think the tool is used to detect ineffectual assignments.

In this case, the tool detect the err is reassigned in the first function,and this is what I need.

But the reassigned err in the second function is not detected, the difference between these two functions is only the first one is a newly declared variable and the second is a pre-declared variable of the function.

I can help take a look, but I'm not sure I can fix it. 😂

**Comment by windard** [comment]
Ok, I got it, when the function panics and recovers, the err assignment is meaningful.

Yes, you are right.

This is a very troublesome problem, I also found this issue in the staticcheck. 

When there is a defer function,the staticcheck can't detect the reassigned err, otherwise can detect.

But it's just check defer function, don't case there is a recover call.

**Comment by gordonklaus** [comment]
Thanks for the report.  Fixed!

**Comment by tarndt** [comment]
@gordonklaus The merging of this fix causes panics against a large code base I work with: https://github.com/gordonklaus/ineffassign/issues/75
