### ISSUE TITLE
Ineff. assignment to local variable not detected in presence of defer or *sync.Mutex

### ISSUE THREAD

**Issue by ainar-g** [gordonklaus/ineffassign#82]
UPD: It seems that the thing that actually prevents `ineffassign` from detecting the error is the `defer`:

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println(f())
}

func f() (n int, err error) {
	n, err = g()
	if err != nil {
		err = fmt.Errorf("g: %w", err)
	}

	defer h()

	return n, nil
}

func g() (n int, err error) { return 0, errors.New("test g") }

func h() {}
```

Removing the `defer` or moving it to the top of `f` lets `ineffassign` detect the issue again.

* * *

```go
package main

import (
	"errors"
	"fmt"
	"sync"
)

func main() {
	fmt.Println(f(&sync.Mutex{}))
}

func f(mu *sync.Mutex) (n int, err error) {
	n, err = g()
	if err != nil {
		err = fmt.Errorf("g: %w", err)
	}

	mu.Lock()
	defer mu.Unlock()

	return n, nil
}

func g() (n int, err error) { return 0, errors.New("test g") }
```

Removing the mutex un/locking makes `ineffassign` detect the ineffectual assignment to `err`.  I've read #81, and there it has been said that:

 >  Any variable accessed in another goroutine is thereafter ignored by the tool.

But there are no accesses of `err` from other goroutines.  Does the tool simply ignore any code with mutexes and other concurrency primitives in it?  If so, can this be improved, or is it not on the agenda?

**Comment by gordonklaus** [comment]
It has to do with `defer`, yes — and also named results and the possibility of panic.

In a function that has named results, at a point where it might possibly panic, if a function has been deferred then it might possibly access one of the named results, thus making any prior assignment to that result effectual.

In your function, the tool recognized that `mu.Unlock()` might panic, and since it saw the `defer` keyword before, it marks all named results as used at that point.

However, there is a subtle error in this analysis:  `mu.Unlock()` might panic, but that actually happens _before_ it is deferred.  Even more subtly, it is only the selector expression `mu.Unlock` that might panic before the defer — the call doesn't happen until the containing function returns (hence your updated function giving the same result).

I'll submit a patch that should fix the analysis of your examples.
